#!/bin/bash

# This script pipes the twitch-api script to dmenu. Then when a user selects one of the urls, it will open that stream in mpv. Simple but affective.

cmd=$(python ~/.local/scripts/twitch-api.py | dmenu  -l 20  -nf '#f8f8f2' -nb '#272822' -sf '#a1efe4' -sb '#75715e' -p 'Select Stream URL')

mpv-play $cmd
